/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:c90c20b5-8512-45db-bb84-1ebe8afca41c",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_KNx2zn0js",
    "aws_user_pools_web_client_id": "67cn7j8rjlb61vjefm7avhb8e",
    "oauth": {}
};


export default awsmobile;
